Training can run now both in local and qsub environments

diff --git a/parallel-kaldi-lat-scale-qsub b/parallel-kaldi-lat-scale-qsub
--- a/parallel-kaldi-lat-scale-qsub
+++ b/parallel-kaldi-lat-scale-qsub
@@ -19,8 +19,12 @@ lm2acoustic_scale=0;
 word_insertion_penalty=0;
 # QSub options
 qsub_opts="-l h_rt=24:00:00,h_vmem=4G";
-# Generic options
+# Custom options
+gzip=true;
 overwrite=false;
+word_symbol_table="";
+write_best_words=false;
+write_best_align=false;
 help_message="
 Usage: parallel-kaldi-lat-scale-qsub [options] lat1 [lat2 ...] work_dir
 
@@ -48,6 +52,8 @@ Options:
   --acoustic2lm_scale          : (float, default = $acoustic2lm_scale)
                                  Add this times original acoustic costs to LM
                                  costs.
+  --gzip                       : (boolean, default = $gzip)
+                                 If true, compress the output files using gzip.
   --inv_acoustic_scale         : (float, default = $inv_acoustic_scale)
                                  An alternative way of setting the acoustic
                                  scale: you can set its inverse. Use this as a
@@ -66,11 +72,22 @@ Options:
                                  Word insertion penalty. Word means the symbols
                                  of the output alphabet in the lattice. This is
                                  equivalent to HTK's word insertion penalty.
+  --word_symbol_table          : (string, default = \"$word_symbol_table\")
+                                 Symbol table for words (for debug output).
+  --write_best_align           : (boolean, default = $write_best_align)
+                                 If true, writes an ARK file with the 1-best
+                                 alignment hypothesis in the output directory.
+  --write_best_words           : (boolean, default = $write_best_words)
+                                 If true, writes an ARK file with the 1-best
+                                 word sequence hypothesis in the output
+                                 directory.
 ";
 . "${SDIR}/parallel-kaldi-cmd-parse.inc.sh" || \
     error "Sourcing file \"${SDIR}/parallel-kaldi-cmd-parse.inc.sh\"";
 [ $# -eq 0 ] && echo "$help_message" >&2 && exit 1;
 [ $# -lt 2 ] && error "Wrong number of arguments. Check the usage with --help";
+[ "$write_best_align" = true ] && write_best_words=true;
+
 lats=();
 while [ $# -gt 1 ]; do lats+=("$1"); shift; done;
 wdir="$1";
@@ -79,12 +96,17 @@ make_dirs "$wdir";
 
 # Check previous results, in order to avoid re-doing work.
 pending_lats=();
-for i in $(seq 1 ${#[@]}); do
+for i in $(seq 1 ${#lats[@]}); do
     olattice="$wdir/lattice.$[i-1].ark";
-    [[ "$overwrite" = false && -s "$olattice" ]] && continue;
+    owords="$wdir/words.$[i-1].ark";
+    oalign="$wdir/align.$[i-1].ark";
+    [[ "$overwrite" = false && $(check_gzipped_files "$olattice") && \
+        ( "$write_best_words" = false || $(check_gzipped_files "$owords") ) && \
+        ( "$write_best_align" = false || $(check_gzipped_files "$oalign") ) ]] \
+        && continue;
     pending_lats+=("$i");
     # Remove previous results, just in case.
-    rm -f "$olattice";
+    rm -f "$olattice"{,.gz} "$owords"{,.gz} "$oalign"{,.gz};
 done;
 if [ ${#pending_lats[@]} -eq 0 ]; then
     # No pending lattices to process. Exit normally.
@@ -106,22 +128,49 @@ cat <<EOF
 set -e;
 EOF
 for i in ${pending_lats[@]}; do
-cat <<EOF
-[[ \${SGE_TASK_ID} -eq $i ]] && {
-  [ "$overwrite" = false -a -s "$wdir/lattice.$[i-1].ark" ] || \\
-    ( lattice-scale --acoustic-scale="$acoustic_scale" \\
-      --acoustic2lm-scale="$acoustic2lm_scale" \\
-      --inv-acoustic-scale="$inv_acoustic_scale" \\
-      --lm-scale="$lm_scale" \\
-      --lm2acoustic_scale="$lm2acoustic_scale" \\
-      "${lats[i-1]}" ark:- | \\
-      lattice-add-penalty --word-ins-penalty="$word_insertion_penalty" \\
-      ark:- "ark:$wdir/lattice.$[i-1].ark" ) \\
-      &> "$wdir/lattice-scale.$[i-1].log" || {
-        echo "\$(date "+%F %T") [${0##*/}:${LINENO}] ERROR: lattice-scale failed, see log file \"$log\"" >&2; exit 1;
-      }
-}
+    olattice="$wdir/lattice.$[i-1].ark";
+    owords="$wdir/words.$[i-1].ark";
+    oalign="$wdir/align.$[i-1].ark";
+    if [ "$gzip" = true ]; then
+        olattice_wspec="ark:|gzip -c -9 > $olattice.gz";
+        olattice_rspec="ark:gunzip -c $olattice.gz|";
+        owords_wspec="ark:|gzip -c -9 > $owords.gz";
+        oalign_wspec="ark:|gzip -c -9 > $oalign.gz";
+    else
+        olattice_wspec="ark:$olattice";
+        olattice_rspec="ark:$olattice";
+        owords_wspec="ark:$owords";
+        oalign_wspec="ark:$oalign";
+    fi;
+    echo "[[ \${SGE_TASK_ID} -eq $i ]] && {";
+    cat <<EOF
+    [[ "$overwrite" = false && ( -s "$olattice" || -s "$olattice.gz" ) ]] || \\
+      ( lattice-scale --acoustic-scale="$acoustic_scale" \\
+        --acoustic2lm-scale="$acoustic2lm_scale" \\
+        --inv-acoustic-scale="$inv_acoustic_scale" \\
+        --lm-scale="$lm_scale" \\
+        --lm2acoustic_scale="$lm2acoustic_scale" \\
+        "${lats[i-1]}" ark:- | \\
+        lattice-add-penalty --word-ins-penalty="$word_insertion_penalty" \\
+        ark:- "$olattice_wspec" ) \\
+        &> "$wdir/lattice-scale.$[i-1].log" || {
+          echo "\$(date "+%F %T") [${0##*/}:${LINENO}] ERROR: lattice-scale failed, see log file \"$wdir/lattice-scale.$[i-1].log\"" >&2; exit 1;
+        }
 EOF
+    if [ "$write_best_words" = true ]; then
+        cat <<EOF
+    [[ "$overwrite" = false && ( -s "$owords" || -s "$owords.gz" ) && \\
+      ( "$write_best_align" = false || -s "$oalign" || -s "$oalign.gz" ) ]] || \\
+      lattice-best-path --acoustic-scale="$acoustic_scale" --lm-scale="$lm_scale" \\
+      --word-symbol-table="$word_symbol_table" "$olattice_rspec" \\
+      "$owords_wspec" \\
+      $([ "$write_best_align" = true ] && echo "\"$oalign_wspec\"") &> "$wdir/lattice-best-path.$[i-1].log" || {
+        echo "\$(date "+%F %T") [${0##*/}:${LINENO}] ERROR: lattice-best-path failed, see log file \"$wdir/lattice-best-path.$[i-1].log\"" >&2; exit 1;
+      }
+EOF
+    fi;
+    echo "}";
+
 done;
 } | qsub | awk '/Your job/{ gsub(/\..*/, "", $3); print $3}' || \
     error "qsub job submission failed!";
diff --git a/parallel-kaldi-viterbi-mle b/parallel-kaldi-viterbi-mle
--- a/parallel-kaldi-viterbi-mle
+++ b/parallel-kaldi-viterbi-mle
@@ -6,13 +6,12 @@ export LC_NUMERIC=C;
 SDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
 ### Load useful functions.
 . "${SDIR}/parallel-kaldi-functions.inc.sh" || ( \
-    echo "ERROR: Sourcing file \"${SDIR}/parallel-kaldi-functions.inc.sh\"">&2 \
-    && exit 1);
+    echo "ERROR: Sourcing file \"${SDIR}/parallel-kaldi-functions.inc.sh\"" >&2 && exit 1);
 
 # Options for gmm-align-compiled
 acoustic_scale=1.0;
 align_equal=true;
-beam=1000;
+beam=10000;
 careful=false;
 retry_beam=0;
 self_loop_scale=1.0;
@@ -28,19 +27,22 @@ transition_min_count=5;
 update_flags=mvwt;
 # MLE iterations
 mle_iterations=10;
-# Generic options
+# QSub options
+qsub=false;
+qsub_opts="-l h_rt=24:00:00,h_vmem=4G";
+# Options for this script
 overwrite=false;
 clean=false;
 help_message="
-Usage: parallel-kaldi-viterbi-mle-local [options] fst1_rspec fea1_rspec
-                                        [fst2_rspec fea2_rspec ...]
-                                        init_mdl work_dir
+Usage: parallel-kaldi-viterbi-mle [options] fst1_rspec fea1_rspec
+                                  [fst2_rspec fea2_rspec ...]
+                                  init_mdl work_dir
 
 Description:
    Perform Maximum Likelihood Estimation of GMM-based acoustic model using
    the statistics from a Viterbi forced alignment.
 
-   e.g: parallel-kaldi-viterbi-mle-local ark:train.fst.1 ark:train.fea.1 \\
+   e.g: parallel-kaldi-viterbi-mle ark:train.fst.1 ark:train.fea.1 \\
         ark:train.fst.2 ark:train.fea.2 init_mdl output_dir
 
 Options:
@@ -73,6 +75,12 @@ Options:
                                  Number of Viterbi MLE iterations.
   --overwrite                  : (boolean, default = $overwrite)
                                  If true, overwrite previously created files.
+  --qsub                       : (boolean, default = $qsub)
+                                 If true, run jobs in a cluster using qsub
+                                 instead of the local machine.
+  --qsub_opts                  : (string, default = \"$qsub_opts\")
+                                 Options passed to the qsub command. Note:
+                                 -cwd and -t are automatically set.
   --remove_low_count_gaussians : (boolean, default = $remove_low_count_gaussians)
                                  If true, remove Gaussians that fall below the
                                  floors.
@@ -107,8 +115,7 @@ while [ $# -gt 2 ]; do fsts_and_feas+=("$1"); shift 1; done;
 old_mdl="$1";
 wdir="$2";
 
-check_execs bc parallel-kaldi-viterbi-mle-iter-local gmm-info gmm-mixup;
-check_files "$old_mdl";
+check_execs bc parallel-kaldi-viterbi-mle-iter gmm-info gmm-mixup;
 make_dirs "$wdir";
 
 # Check option values
@@ -118,7 +125,7 @@ make_dirs "$wdir";
 # Perform --mle_iterations iterations of the MLE with Viterbi alignment.
 for k in $(seq 1 $mle_iterations); do
     msg "--- Viterbi MLE iteration $k (of $mle_iterations)";
-    parallel-kaldi-viterbi-mle-iter-local \
+    hold_jid=$(parallel-kaldi-viterbi-mle-iter \
 	--align_equal \
 	$(if [ $k = 1 ]; then echo $align_equal; else echo false; fi) \
 	--acoustic_scale "$acoustic_scale" \
@@ -127,6 +134,7 @@ for k in $(seq 1 $mle_iterations); do
 	--min_gaussian_weight "$min_gaussian_weight" \
 	--min_variance "$min_variance" \
 	--overwrite "$overwrite" \
+        --qsub "$qsub" --qsub_opts "$qsub_opts $qsub_hold_jid" \
 	--remove_low_count_gaussians "$remove_low_count_gaussians" \
 	--retry_beam "$retry_beam" \
 	--self_loop_scale "$self_loop_scale" \
@@ -135,9 +143,14 @@ for k in $(seq 1 $mle_iterations); do
 	--transition_min_count "$transition_min_count" \
 	--transition_scale "$transition_scale" \
 	--update_flags "$update_flags" "${fsts_and_feas[@]}" \
-	"$old_mdl" "${wdir}/it_${k}" || exit 1;
+	"$old_mdl" "${wdir}/it_${k}") || exit 1;
     # Point old_mdl to the newest model.
     old_mdl="${wdir}/it_${k}/mdl";
+    # If running in qsub, next iteration must wait for the current one.
+    [ -z "$hold_jid" ] || qsub_hold_jid="-hold_jid $hold_jid";
 done;
+
+# Print job id of the latest iteration, so scripts calling this can wait.
+[ "$qsub" = true -a -n "$hold_jid" ] && echo "$hold_jid";
 
 exit 0;
diff --git a/parallel-kaldi-viterbi-mle-iter b/parallel-kaldi-viterbi-mle-iter
--- a/parallel-kaldi-viterbi-mle-iter
+++ b/parallel-kaldi-viterbi-mle-iter
@@ -6,13 +6,12 @@ export LC_NUMERIC=C;
 SDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
 ### Load useful functions.
 . "${SDIR}/parallel-kaldi-functions.inc.sh" || ( \
-    echo "ERROR: Sourcing file \"${SDIR}/parallel-kaldi-functions.inc.sh\"">&2 \
-    && exit 1);
+    echo "ERROR: Sourcing file \"${SDIR}/parallel-kaldi-functions.inc.sh\"" >&2 && exit 1);
 
 # Options for gmm-align-compiled
 acoustic_scale=1.0;
 align_equal=false;
-beam=1000;
+beam=10000;
 careful=false;
 retry_beam=0;
 self_loop_scale=1.0;
@@ -26,19 +25,22 @@ share_for_pdfs=false;
 transition_floor=0.01;
 transition_min_count=5;
 update_flags=mvwt;
-# Generic options
+# QSub options
+qsub=false;
+qsub_opts="-l h_rt=24:00:00,h_vmem=4G";
+# Options for this script
 overwrite=false;
 clean=false;
 help_message="
-Usage: parallel-kaldi-mle-viterbi-iter-local [options] fst1_rspec fea1_rspec
-                                             [fst2_rspec fea2_rspec ...]
-                                             old_mdl work_dir
+Usage: parallel-kaldi-viterbi-mle-iter [options] fst1_rspec fea1_rspec
+                                       [fst2_rspec fea2_rspec ...]
+                                       old_mdl work_dir
 
 Description:
    Perform Maximum Likelihood Estimation of GMM-based acoustic model using
    the statistics from a Viterbi forced alignment.
 
-   e.g: parallel-kaldi-mle-viterbi-iter-local \\
+   e.g: parallel-kaldi-viterbi-mle-iter \\
         ark:train.fst.1 ark:train.fea.1 ark:train.fst.2 ark:train.fea.2 \\
         old_mdl output_dir
 
@@ -69,6 +71,12 @@ Options:
                                  Variance floor (absolute variance).
   --overwrite                  : (boolean, default = $overwrite)
                                  If true, overwrite previously created files.
+  --qsub                       : (boolean, default = $qsub)
+                                 If true, run jobs in a cluster using qsub
+                                 instead of the local machine.
+  --qsub_opts                  : (string, default = \"$qsub_opts\")
+                                 Options passed to the qsub command. Note:
+                                 -cwd and -t are automatically set.
   --remove_low_count_gaussians : (boolean, default = $remove_low_count_gaussians)
                                  If true, remove Gaussians that fall below the
                                  floors.
@@ -107,8 +115,7 @@ old_mdl="$1";
 wdir="$2";
 
 check_execs bc align-equal-compiled gmm-align-compiled gmm-acc-stats-ali \
-    gmm-est gmm-sum-accs;
-check_files "$old_mdl";
+    gmm-est gmm-sum-accs qsub;
 make_dirs "$wdir";
 
 # Check option values
@@ -135,22 +142,99 @@ make_dirs "$wdir";
 
 # If there is a trained model and pdf occupation counts in the output directory
 # and --overwrite = false, then we are done: the script can exit safely.
-[ -s "${wdir}/mdl" -a -s "${wdir}/occ" -a $overwrite = false ] && exit 0;
+[ -s "${wdir}/mdl" -a -s "${wdir}/occ" -a "$overwrite" = false ] && exit 0;
 
-# Launch background processes to perform forced alignment and statistics
-# accumulation. Each process write its own output and log file in the working
-# directory. Process are only launched if the corresponding output file is
-# not empty, or --overwrite = true.
-bg_jobs=();
-accs=();
-for i in $(seq 0 $[${#fsts[@]} - 1]); do
+# In order to avoid scheduling jobs that won't do anything useful, check which
+# statistics tasks were already completed, and schedule only those that were
+# not.
+pending_tasks=(); accs=();
+for i in $(seq 1 ${#fsts[@]}); do
     acc="${wdir}/acc.$i";
     log="${wdir}/gmm-acc-stats-ali.$i.log";
     accs+=("$acc");
-    [ -s "$acc" -a $overwrite = false ] || {
+    [ -s "$acc" -a "$overwrite" = false ] && \
+        grep -q "Overall avg like" "$log" && continue;
+    pending_tasks+=("$i");
+    rm -f "$acc" "$log";
+done;
+
+if [ $qsub = true ]; then
+    # First, compute statistics from each of the input fsts/features.
+    hold_jid=$(if [ ${#pending_tasks[@]} -gt 0 ]; then
+    if [ ${#pending_tasks[@]} -eq ${#fsts[@]} ]; then
+        # All input feature partitions must be processed.
+        qsub_tasks="1-${#fsts[@]}";
+    else
+        # Only a subset of the input features must be processed.
+        qsub_tasks="$(echo "${pending_fsts[@]}" | sed "s| |,|g")";
+    fi;
+    ( cat <<EOF
+#!/bin/bash
+#$ -cwd
+#$ -t ${qsub_tasks}
+#$ ${qsub_opts}
+EOF
+    for i in "${pending_tasks[@]}"; do
+        acc="${wdir}/acc.$i";
+        log="${wdir}/gmm-acc-stats-ali.$i.log";
+        if [ "$align_equal" = true ]; then
+            cat <<EOF
+[ \${SGE_TASK_ID} -eq $i ] && {
+  ( align-equal-compiled "${fsts[i-1]}" "${feas[i-1]}" ark:- | \
+    gmm-acc-stats-ali "$old_mdl" "${feas[i-1]}" ark:- "$acc" ) &> "$log" || \
+    exit 1;
+  exit 0;
+}
+EOF
+        else
+            cat <<EOF
+[ \${SGE_TASK_ID} -eq $i ] && {
+  ( gmm-align-compiled \
+    --acoustic_scale=$acoustic_scale --beam=$beam --careful=$careful \
+    --retry_beam=$retry_beam --self_loop_scale=$self_loop_scale \
+    --transition_scale=$transition_scale "$old_mdl" "${fsts[i-1]}" \
+    "${feas[i-1]}" ark:- | gmm-acc-stats-ali "$old_mdl" "${feas[i-1]}" \
+    ark:- "$acc" ) &> "$log" || exit 1;
+  exit 0;
+}
+EOF
+        fi;
+    done ) | qsub | awk '/Your job/{ gsub(/\..*/, "", $3); print $3}' || \
+        error "qsub job submission failed!";
+    fi) || exit 1;
+    # Hold next command to pending statistics accumulation?
+    [ -z "$hold_jid" ] || hold_jid="-hold_jid $hold_jid";
+
+    # Perform MLE of the parameters from the statistics computed before and
+    # write a new model to $wdir/mdl.
+    ( cat <<EOF
+#!/bin/bash
+#$ -cwd
+#$ ${qsub_opts}
+#$ ${hold_jid}
+gmm-est --min-gaussian-occupancy=$min_gaussian_occupancy \
+  --min-gaussian-weight=$min_gaussian_weight --min-variance=$min_variance \
+  --remove-low-count-gaussians=$remove_low_count_gaussians \
+  --share-for-pdfs=$share_for_pdfs --transition-floor=$transition_floor \
+  --transition-min-count=$transition_min_count --write-occs="${wdir}/occ" \
+  --update-flags="$update_flags" "$old_mdl" "gmm-sum-accs - ${accs[@]}|" \
+  "${wdir}/mdl" &> "${wdir}/gmm-est.log" || ( \
+  echo "\$(date "+%F %T") [${0##*/}:${LINENO}] ERROR: Maximum Likelihood Estimation failed, see \"${wdir}/gmm-est.log\"" && exit 1 );
+
+# Clean temporal files with the accumulated statistics (optionally) and exit.
+[ $clean = false ] || rm -f ${accs[@]} || exit 1;
+exit 0;
+EOF
+    ) | qsub | awk '/Your job/{ gsub(/\..*/, "", $3); print $3}' || \
+        error "qsub job submission failed!";
+else
+    bg_jobs=();
+    for i in "${pending_tasks[@]}"; do
+        acc="${wdir}/acc.$i";
+        log="${wdir}/gmm-acc-stats-ali.$i.log";
 	if [ $align_equal = true ]; then
-	    ( align-equal-compiled "${fsts[i]}" "${feas[i]}" ark:- | \
-		gmm-acc-stats-ali "$old_mdl" "${feas[i]}" ark:- "$acc" ) \
+	    ( align-equal-compiled "${fsts[i-1]}" "${feas[i-1]}" ark:- | \
+		gmm-acc-stats-ali "$old_mdl" "${feas[i-1]}" ark:- "$acc" ) \
 		&> "$log" &
 	    bg_jobs+=("$!");
 	else
@@ -158,40 +242,37 @@ for i in $(seq 0 $[${#fsts[@]} - 1]); do
 		--acoustic_scale=$acoustic_scale --beam=$beam \
 		--careful=$careful --retry_beam=$retry_beam \
 		--self_loop_scale=$self_loop_scale \
-		--transition_scale=$transition_scale "$old_mdl" "${fsts[i]}" \
-		"${feas[i]}" ark:- | \
-		gmm-acc-stats-ali "$old_mdl" "${feas[i]}" ark:- "$acc" ) \
+		--transition_scale=$transition_scale "$old_mdl" \
+                "${fsts[i-1]}" "${feas[i-1]}" ark:- | \
+		gmm-acc-stats-ali "$old_mdl" "${feas[i-1]}" ark:- "$acc" ) \
 		&> "$log" &
 	    bg_jobs+=("$!");
 	fi;
-    }
-done;
-
-# Wait for all processes running in the background.
-any_failure=0;
-for i in $(seq 0 $[${#bg_jobs[@]} - 1]); do
-    log="${wdir}/gmm-acc-stats-ali.$i.log";
-    wait ${bg_jobs[i]} || ( \
-	error_continue "Worker computing statistics failed, see \"$log\"" && \
-	any_failure=1 );
-done;
-[ $any_failure -eq 0 ] || exit 1;
-
-# Perform MLE of the parameters from the statistics computed before and write
-# a new model to $wdir/mdl.
-[ -s "${wdir}/mdl" -a -s "${wdir}/occ" -a "${overwrite}" = false ] || \
+    done;
+    # Wait for all processes running in the background.
+    any_failure=0;
+    for i in $(seq 1 ${#bg_jobs[@]}); do
+        log="${wdir}/gmm-acc-stats-ali.$i.log";
+        wait ${bg_jobs[i-1]} || ( \
+	    error_continue "Worker failed, see \"$log\"" && any_failure=1 );
+    done;
+    [ $any_failure -eq 0 ] || exit 1;
+    # Perform MLE of the parameters from the statistics computed before and
+    # write a new model to $wdir/mdl.
     gmm-est --min-gaussian-occupancy=$min_gaussian_occupancy \
-    --min-gaussian-weight=$min_gaussian_weight \
-    --min-variance=$min_variance \
-    --remove-low-count-gaussians=$remove_low_count_gaussians \
-    --share-for-pdfs=$share_for_pdfs \
-    --transition-floor=$transition_floor \
-    --transition-min-count=$transition_min_count \
-    --update-flags="$update_flags" --write-occs="${wdir}/occ" \
-    "$old_mdl" "gmm-sum-accs - $(echo "${accs[@]}")|" "${wdir}/mdl" \
-    &> "${wdir}/gmm-est.log" || \
-    error "Maximum Likelihood Estimation failed, see \"${wdir}/gmm-est.log\"";
+        --min-gaussian-weight=$min_gaussian_weight \
+        --min-variance=$min_variance \
+        --remove-low-count-gaussians=$remove_low_count_gaussians \
+        --share-for-pdfs=$share_for_pdfs \
+        --transition-floor=$transition_floor \
+        --transition-min-count=$transition_min_count \
+        --update-flags="$update_flags" --write-occs="${wdir}/occ" \
+        "$old_mdl" "gmm-sum-accs - ${accs[@]}|" "${wdir}/mdl" \
+        &> "${wdir}/gmm-est.log" || error \
+        "Maximum Likelihood Estimation failed, see \"${wdir}/gmm-est.log\"";
+    # Clean temporal files with the accumulated statistics (optionally) and
+    # exit.
+    [ $clean = false ] || rm -f ${accs[@]} || exit 1;
+fi;
 
-# Clean temporal files with the accumulated statistics (optionally) and exit.
-[ $clean = false ] || rm -f ${accs[@]} || exit 1;
 exit 0;
diff --git a/parallel-kaldi-viterbi-train b/parallel-kaldi-viterbi-train
--- a/parallel-kaldi-viterbi-train
+++ b/parallel-kaldi-viterbi-train
@@ -12,7 +12,7 @@ SDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
 # Options for gmm-align-compiled
 acoustic_scale=1.0;
 align_equal=true;
-beam=1000;
+beam=10000;
 careful=false;
 retry_beam=0;
 self_loop_scale=1.0;
@@ -34,13 +34,16 @@ num_gaussian_scale=2;
 min_count=20;
 perturb_factor=0.01;
 power=0.2;
+# QSub options
+qsub=false;
+qsub_opts="-l h_rt=24:00:00,h_vmem=4G";
 # Generic options
 overwrite=false;
 clean=false;
 help_message="
-Usage: parallel-kaldi-viterbi-train-local [options] fst1_rspec fea1_rspec
-                                          [fst2_rspec fea2_rspec ...]
-                                          init_mdl work_dir
+Usage: parallel-kaldi-viterbi-train [options] fst1_rspec fea1_rspec
+                                    [fst2_rspec fea2_rspec ...]
+                                    init_mdl work_dir
 
 Description:
    Perform traditional training of a GMM-based acoustic model using the
@@ -48,7 +51,7 @@ Description:
    with 1 (or a few number of) gaussian mixture(s) and increases this number
    after a few iterations of Viterbi MLE training.
 
-   e.g: parallel-kaldi-viterbi-train-local ark:train.fst.1 ark:train.fea.1 \\
+   e.g: parallel-kaldi-viterbi-train ark:train.fst.1 ark:train.fea.1 \\
         ark:train.fst.2 ark:train.fea.2 init_mdl output_dir
 
 Options:
@@ -98,6 +101,12 @@ Options:
   --power                      : (float, default = $power)
                                  Power to allocate Gaussians to states while
                                  mixing up.
+  --qsub                       : (boolean, default = $qsub)
+                                 If true, run jobs in a cluster using qsub
+                                 instead of the local machine.
+  --qsub_opts                  : (string, default = \"$qsub_opts\")
+                                 Options passed to the qsub command. Note:
+                                 -cwd and -t are automatically set.
   --remove_low_count_gaussians : (boolean, default = $remove_low_count_gaussians)
                                  If true, remove Gaussians that fall below the
                                  floors.
@@ -132,8 +141,7 @@ while [ $# -gt 2 ]; do fsts_and_feas+=("$1"); shift 1; done;
 old_mdl="$1";
 wdir="$2";
 
-check_execs bc parallel-kaldi-viterbi-mle-local gmm-info gmm-mixup;
-check_files "$old_mdl";
+check_execs bc parallel-kaldi-viterbi-mle gmm-info gmm-mixup;
 make_dirs "$wdir";
 
 # Check option values
@@ -179,13 +187,14 @@ for i in $(seq 1 ${#num_gaussian[@]}); do
     # Perform equal alignment only for the first iteration.
     [ $i -gt 1 ] && align_equal=false;
     msg "+++ Training with $cg (of $final_gaussian) gaussian mixtures";
-    parallel-kaldi-viterbi-mle-local \
+    hold_jid=$(parallel-kaldi-viterbi-mle \
 	--align_equal "$align_equal" --acoustic_scale "$acoustic_scale" \
 	--beam "$beam" --careful "$careful" --clean "$clean" \
 	--min_gaussian_occupancy "$min_gaussian_occupancy" \
 	--min_gaussian_weight "$min_gaussian_weight" \
 	--min_variance "$min_variance" --mle_iterations "$mle_iterations" \
-	--overwrite "$overwrite" \
+	--overwrite "$overwrite" --qsub "$qsub" \
+        --qsub_opts "$qsub_opts $qsub_hold_jid" \
 	--remove_low_count_gaussians "$remove_low_count_gaussians" \
 	--retry_beam "$retry_beam" --self_loop_scale "$self_loop_scale" \
 	--share_for_pdfs "$share_for_pdfs" \
@@ -193,7 +202,9 @@ for i in $(seq 1 ${#num_gaussian[@]}); do
 	--transition_min_count "$transition_min_count" \
 	--transition_scale "$transition_scale" \
 	--update_flags "$update_flags" "${fsts_and_feas[@]}" \
-	"$old_mdl" "${wdir}/gmm_${cg}" || exit 1;
+	"$old_mdl" "${wdir}/gmm_${cg}") || exit 1;
+    # If running in qsub, next iteration must wait for the current one.
+    [ -z "$hold_jid" ] || qsub_hold_jid="-hold_jid $hold_jid";
     # Point old_mdl to the newest model and old_occ to the p.d.f. occupancies.
     old_mdl="${wdir}/gmm_${cg}/it_${mle_iterations}/mdl";
     old_occ="${wdir}/gmm_${cg}/it_${mle_iterations}/occ";
@@ -203,11 +214,29 @@ for i in $(seq 1 ${#num_gaussian[@]}); do
 	log="${wdir}/gmm_${num_gaussian[i]}/it_0/gmm-mixup.log";
 	make_dirs "${wdir}/gmm_${num_gaussian[i]}/it_0";
 	[ -s "$mdl" -a $overwrite = false ] || \
+            if [ $qsub = true ]; then
+            hold_jid=$(( cat <<EOF
+#!/bin/bash
+#$ -cwd
+#$ ${qsub_opts}
+#$ ${qsub_hold_jid}
+gmm-mixup --min-count="$min_count" \
+    --mix-up="$[${num_gaussian[i]} * $total_pdfs]" \
+    --perturb-factor="$perturb_factor" --power="$power" \
+    "$old_mdl" "$old_occ" "$mdl" &> "$log" || ( \
+  echo "\$(date "+%F %T") [${0##*/}:${LINENO}] ERROR: GMM mixing up failed, see log file \"$log\"!" && exit 1 );
+EOF
+            ) | qsub | awk '/Your job/{ gsub(/\..*/, "", $3); print $3}' || \
+               error "qsub job submission failed!") || exit 1;
+            # If running in qsub, next iteration must wait for the current one.
+            [ -z "$hold_jid" ] || qsub_hold_jid="-hold_jid $hold_jid";
+        else
 	    gmm-mixup --min-count="$min_count" \
-	    --mix-up="$[${num_gaussian[i]} * $total_pdfs]" \
-	    --perturb-factor="$perturb_factor" --power="$power" \
-	    "$old_mdl" "$old_occ" "$mdl" &> "$log" || \
-	    error "GMM mixing up failed, see log file \"$log\"";
+	        --mix-up="$[${num_gaussian[i]} * $total_pdfs]" \
+	        --perturb-factor="$perturb_factor" --power="$power" \
+	        "$old_mdl" "$old_occ" "$mdl" &> "$log" || \
+	        error "GMM mixing up failed, see log file \"$log\"";
+        fi;
 	old_mdl="$mdl";
     fi;
 done;
